name: Backend Checkstyle & Build

on: [push, pull_request]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: JDK 17 kur
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven ile derle
        run: mvn clean install -DskipTests

      - name: Checkstyle çalıştır
        run: mvn checkstyle:check
