name: Dockerfile Lint

on: [push, pull_request]

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Dockerfile'ı kontrol et
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
